//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("September22.DAL", "FK_Guest_DinnerPreference", "DinnerPreference", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(September22.DAL.DinnerPreference), "Guest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(September22.DAL.Guest), true)]
[assembly: EdmRelationshipAttribute("September22.DAL", "FK_Guest_Invitation", "Invitation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(September22.DAL.Invitation), "Guest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(September22.DAL.Guest), true)]

#endregion

namespace September22.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WeddingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WeddingEntities object using the connection string found in the 'WeddingEntities' section of the application configuration file.
        /// </summary>
        public WeddingEntities() : base("name=WeddingEntities", "WeddingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WeddingEntities object.
        /// </summary>
        public WeddingEntities(string connectionString) : base(connectionString, "WeddingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WeddingEntities object.
        /// </summary>
        public WeddingEntities(EntityConnection connection) : base(connection, "WeddingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DinnerPreference> DinnerPreferences
        {
            get
            {
                if ((_DinnerPreferences == null))
                {
                    _DinnerPreferences = base.CreateObjectSet<DinnerPreference>("DinnerPreferences");
                }
                return _DinnerPreferences;
            }
        }
        private ObjectSet<DinnerPreference> _DinnerPreferences;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Guest> Guests
        {
            get
            {
                if ((_Guests == null))
                {
                    _Guests = base.CreateObjectSet<Guest>("Guests");
                }
                return _Guests;
            }
        }
        private ObjectSet<Guest> _Guests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Invitation> Invitations
        {
            get
            {
                if ((_Invitations == null))
                {
                    _Invitations = base.CreateObjectSet<Invitation>("Invitations");
                }
                return _Invitations;
            }
        }
        private ObjectSet<Invitation> _Invitations;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DinnerPreferences EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDinnerPreferences(DinnerPreference dinnerPreference)
        {
            base.AddObject("DinnerPreferences", dinnerPreference);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Guests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGuests(Guest guest)
        {
            base.AddObject("Guests", guest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Invitations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInvitations(Invitation invitation)
        {
            base.AddObject("Invitations", invitation);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="September22.DAL", Name="DinnerPreference")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DinnerPreference : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DinnerPreference object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static DinnerPreference CreateDinnerPreference(global::System.Int32 id)
        {
            DinnerPreference dinnerPreference = new DinnerPreference();
            dinnerPreference.ID = id;
            return dinnerPreference;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("September22.DAL", "FK_Guest_DinnerPreference", "Guest")]
        public EntityCollection<Guest> Guests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Guest>("September22.DAL.FK_Guest_DinnerPreference", "Guest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Guest>("September22.DAL.FK_Guest_DinnerPreference", "Guest", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="September22.DAL", Name="Guest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Guest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Guest object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="invitationID">Initial value of the InvitationID property.</param>
        /// <param name="fullName">Initial value of the FullName property.</param>
        public static Guest CreateGuest(global::System.Int32 id, global::System.Int32 invitationID, global::System.String fullName)
        {
            Guest guest = new Guest();
            guest.ID = id;
            guest.InvitationID = invitationID;
            guest.FullName = fullName;
            return guest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InvitationID
        {
            get
            {
                return _InvitationID;
            }
            set
            {
                OnInvitationIDChanging(value);
                ReportPropertyChanging("InvitationID");
                _InvitationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvitationID");
                OnInvitationIDChanged();
            }
        }
        private global::System.Int32 _InvitationID;
        partial void OnInvitationIDChanging(global::System.Int32 value);
        partial void OnInvitationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DinnerPreferenceID
        {
            get
            {
                return _DinnerPreferenceID;
            }
            set
            {
                OnDinnerPreferenceIDChanging(value);
                ReportPropertyChanging("DinnerPreferenceID");
                _DinnerPreferenceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DinnerPreferenceID");
                OnDinnerPreferenceIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DinnerPreferenceID;
        partial void OnDinnerPreferenceIDChanging(Nullable<global::System.Int32> value);
        partial void OnDinnerPreferenceIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("September22.DAL", "FK_Guest_DinnerPreference", "DinnerPreference")]
        public DinnerPreference DinnerPreference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DinnerPreference>("September22.DAL.FK_Guest_DinnerPreference", "DinnerPreference").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DinnerPreference>("September22.DAL.FK_Guest_DinnerPreference", "DinnerPreference").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DinnerPreference> DinnerPreferenceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DinnerPreference>("September22.DAL.FK_Guest_DinnerPreference", "DinnerPreference");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DinnerPreference>("September22.DAL.FK_Guest_DinnerPreference", "DinnerPreference", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("September22.DAL", "FK_Guest_Invitation", "Invitation")]
        public Invitation Invitation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Invitation>("September22.DAL.FK_Guest_Invitation", "Invitation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Invitation>("September22.DAL.FK_Guest_Invitation", "Invitation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Invitation> InvitationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Invitation>("September22.DAL.FK_Guest_Invitation", "Invitation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Invitation>("September22.DAL.FK_Guest_Invitation", "Invitation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="September22.DAL", Name="Invitation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Invitation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Invitation object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="maxNumberOfGuests">Initial value of the MaxNumberOfGuests property.</param>
        public static Invitation CreateInvitation(global::System.Int32 id, global::System.String firstName, global::System.String lastName, global::System.Byte maxNumberOfGuests)
        {
            Invitation invitation = new Invitation();
            invitation.ID = id;
            invitation.FirstName = firstName;
            invitation.LastName = lastName;
            invitation.MaxNumberOfGuests = maxNumberOfGuests;
            return invitation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte MaxNumberOfGuests
        {
            get
            {
                return _MaxNumberOfGuests;
            }
            set
            {
                OnMaxNumberOfGuestsChanging(value);
                ReportPropertyChanging("MaxNumberOfGuests");
                _MaxNumberOfGuests = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxNumberOfGuests");
                OnMaxNumberOfGuestsChanged();
            }
        }
        private global::System.Byte _MaxNumberOfGuests;
        partial void OnMaxNumberOfGuestsChanging(global::System.Byte value);
        partial void OnMaxNumberOfGuestsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Attending
        {
            get
            {
                return _Attending;
            }
            set
            {
                OnAttendingChanging(value);
                ReportPropertyChanging("Attending");
                _Attending = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Attending");
                OnAttendingChanged();
            }
        }
        private Nullable<global::System.Boolean> _Attending;
        partial void OnAttendingChanging(Nullable<global::System.Boolean> value);
        partial void OnAttendingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("September22.DAL", "FK_Guest_Invitation", "Guest")]
        public EntityCollection<Guest> Guests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Guest>("September22.DAL.FK_Guest_Invitation", "Guest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Guest>("September22.DAL.FK_Guest_Invitation", "Guest", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
